http:
  routers:
    backend:
      rule: "PathPrefix(`/api`)"
      service: backend

    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000/"

    backend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001/"
